# © Noah Flood 2025

# This list is useful for testing because it includes:
# - Short palindromes (madam, pop)
# - Long palindromes (step on no pets, wasitacaroracatisaw)
# - Short almost-palindromes (abca, leveel)
# - Long almost-palindromes (neveroddorevenx, helloollehx)
# - Normal words (apple, python, basketball).

# Deprecated
# all the palindromes from the above list concatenated together. do not change if you want to use the built in testing system.
# checker = "madamracecarleveldeedrotornooncivicreferkayakpopstep on no petsredderwowrepapermomdadabbaeyeradarraceecarrevverrefferwasitacaroracatisawkayyakmomompalindromemordnilap"

string_pool_deprecated = [
    "madam", "racecar", "level", "deed", "rotor", "noon", "civic", "refer", "kayak", "pop",
    "step on no pets", "never odd or even", "redder", "wow", "repaper", "mom", "dad", "abba", "eye", "radar",
    "apple", "banana", "mountain", "computer", "university", "basketball", "friendship", "notapalindrome", "python", "guitar",
    "abca", "abcdcaa", "raceecar", "leveel", "noonn", "civicc", "revver", "rotorr", "madamm", "reffer",
    "wasitacaroracatisaw", "neveroddorevenx", "almosttomsla", "helloollehx", "step on no petss", "kayyak", "momom", "referx", "palindromemordnilap", "deedd"
]

# Expanded test string pool for palindrome testing (~1000 long)
string_pool = [
    "madam",
    "racecar",
    "level",
    "deed",
    "rotor",
    "noon",
    "civic",
    "refer",
    "kayak",
    "pop",
    "step on no pets",
    "never odd or even",
    "redder",
    "wow",
    "repaper",
    "mom",
    "dad",
    "abba",
    "eye",
    "radar",
    "apple",
    "banana",
    "mountain",
    "computer",
    "university",
    "basketball",
    "friendship",
    "notapalindrome",
    "python",
    "guitar",
    "abca",
    "abcdcaa",
    "raceecar",
    "leveel",
    "noonn",
    "civicc",
    "revver",
    "rotorr",
    "madamm",
    "reffer",
    "wasitacaroracatisaw",
    "neveroddorevenx",
    "almosttomsla",
    "helloollehx",
    "step on no petss",
    "kayyak",
    "momom",
    "referx",
    "palindromemordnilap",
    "deedd",
    "do geese see god",
    "a man a plan a canal panama",
    "madam in eden im adam",
    "peep",
    "eke",
    "bottle",
    "helloo",
    "a man a plan a canal panamax",
    "gig",
    "peep",
    "rotorr",
    "never a foot too far even",
    "nun",
    "a man a plan a canal panama",
    "do geese see god",
    "orange",
    "madam in eden im adamm",
    "bob",
    "peep",
    "a man a plan a canal panama",
    "tot",
    "table",
    "chair",
    "a man a plan a canal panama",
    "did",
    "music",
    "science",
    "never a foot too far even",
    "do geese see god",
    "helloo",
    "wow",
    "eke",
    "phone",
    "phone",
    "a man a plan a canal panama",
    "orange",
    "pip",
    "a man a plan a canal panamax",
    "civiv",
    "bottle",
    "civiv",
    "nun",
    "school",
    "orange",
    "science",
    "school",
    "desk",
    "wow",
    "table",
    "pip",
    "phone",
    "helloo",
    "rotorr",
    "tot",
    "was it a car or a cat i saw",
    "bottle",
    "table",
    "desk",
    "do geese see godx",
    "helloo",
    "did",
    "bob",
    "music",
    "bob",
    "never a foot too far even",
    "nan",
    "a man a plan a canal panama",
    "rotorr",
    "helloo",
    "chair",
    "evil olive",
    "gig",
    "did",
    "tot",
    "window",
    "abcb",
    "a man a plan a canal panamax",
    "peep",
    "school",
    "orange",
    "did",
    "madam in eden im adamm",
    "gig",
    "window",
    "nooon",
    "bottle",
    "nun",
    "peep",
    "pip",
    "bob",
    "civiv",
    "wow",
    "never odd or evenn",
    "chair",
    "rotorr",
    "music",
    "evil olive",
    "do geese see god",
    "peep",
    "helloo",
    "abcb",
    "levvel",
    "nan",
    "a man a plan a canal panama",
    "orange",
    "science",
    "eke",
    "gig",
    "nun",
    "science",
    "was it a car or a cat i saw",
    "wow",
    "was it a car or a cat i saw",
    "nun",
    "wow",
    "nooon",
    "rotorr",
    "pip",
    "evil olive",
    "was it a car or a cat i saw",
    "rotorr",
    "science",
    "madam in eden im adamm",
    "nan",
    "school",
    "did",
    "chair",
    "do geese see god",
    "helloo",
    "table",
    "tot",
    "science",
    "abcb",
    "nooon",
    "nun",
    "gig",
    "music",
    "nan",
    "peep",
    "bob",
    "orange",
    "eke",
    "music",
    "phone",
    "wow",
    "never a foot too far even",
    "chair",
    "peep",
    "eke",
    "peep",
    "bottle",
    "was it a car or a cat i saw",
    "tot",
    "orange",
    "pip",
    "pip",
    "never a foot too far even",
    "nan",
    "madam in eden im adamm",
    "school",
    "was it a car or a cat i saw",
    "wow",
    "was it a car or a cat i saw",
    "abcb",
    "table",
    "a man a plan a canal panamax",
    "table",
    "orange",
    "desk",
    "chair",
    "pip",
    "gig",
    "science",
    "tot",
    "window",
    "window",
    "was it a car or a cat i saw",
    "nan",
    "table",
    "window",
    "never odd or evenn",
    "table",
    "nooon",
    "eke",
    "school",
    "abcb",
    "chair",
    "evil olive",
    "gig",
    "never a foot too far even",
    "orange",
    "chair",
    "school",
    "do geese see godx",
    "nan",
    "was it a car or a cat i saw",
    "helloo",
    "did",
    "peep",
    "levvel",
    "pip",
    "window",
    "wow",
    "phone",
    "pip",
    "desk",
    "was it a car or a cat i saw",
    "abcb",
    "gig",
    "never odd or evenn",
    "madam in eden im adam",
    "music",
    "did",
    "evil olive",
    "window",
    "do geese see godx",
    "pip",
    "eke",
    "desk",
    "was it a car or a cat i saw",
    "a man a plan a canal panamax",
    "eke",
    "tot",
    "rotorr",
    "evil olive",
    "gig",
    "nun",
    "nooon",
    "do geese see godx",
    "abcb",
    "desk",
    "levvel",
    "nan",
    "never a foot too far even",
    "wow",
    "madam in eden im adamm",
    "nan",
    "a man a plan a canal panama",
    "music",
    "phone",
    "phone",
    "evil olive",
    "madam in eden im adamm",
    "bob",
    "a man a plan a canal panamax",
    "desk",
    "nun",
    "do geese see god",
    "did",
    "pip",
    "table",
    "school",
    "bottle",
    "wow",
    "did",
    "wow",
    "bottle",
    "do geese see god",
    "bob",
    "nooon",
    "peep",
    "rotorr",
    "evil olive",
    "school",
    "science",
    "a man a plan a canal panama",
    "rotorr",
    "helloo",
    "school",
    "peep",
    "bottle",
    "never a foot too far even",
    "nooon",
    "do geese see god",
    "gig",
    "pip",
    "never odd or evenn",
    "chair",
    "wow",
    "nooon",
    "wow",
    "eke",
    "bob",
    "science",
    "rotorr",
    "bob",
    "window",
    "window",
    "wow",
    "window",
    "nun",
    "wow",
    "desk",
    "do geese see godx",
    "nan",
    "nooon",
    "madam in eden im adamm",
    "wow",
    "helloo",
    "school",
    "wow",
    "phone",
    "did",
    "nan",
    "music",
    "do geese see god",
    "wow",
    "nooon",
    "school",
    "bottle",
    "do geese see god",
    "desk",
    "phone",
    "chair",
    "wow",
    "never odd or evenn",
    "music",
    "was it a car or a cat i saw",
    "chair",
    "nan",
    "bob",
    "nun",
    "window",
    "chair",
    "civiv",
    "levvel",
    "madam in eden im adam",
    "evil olive",
    "madam in eden im adamm",
    "abcb",
    "eke",
    "evil olive",
    "music",
    "evil olive",
    "do geese see godx",
    "was it a car or a cat i saw",
    "pip",
    "window",
    "nun",
    "madam in eden im adamm",
    "gig",
    "civiv",
    "levvel",
    "gig",
    "levvel",
    "never odd or evenn",
    "table",
    "gig",
    "madam in eden im adamm",
    "phone",
    "nun",
    "desk",
    "never a foot too far even",
    "eke",
    "madam in eden im adamm",
    "tot",
    "desk",
    "science",
    "bob",
    "phone",
    "nun",
    "did",
    "madam in eden im adamm",
    "a man a plan a canal panamax",
    "civiv",
    "madam in eden im adamm",
    "bottle",
    "a man a plan a canal panamax",
    "never a foot too far even",
    "pip",
    "window",
    "window",
    "levvel",
    "eke",
    "school",
    "tot",
    "madam in eden im adam",
    "science",
    "a man a plan a canal panamax",
    "pip",
    "was it a car or a cat i saw",
    "music",
    "able was I ere I saw elba",
    "do geese see godx",
    "school",
    "orange",
    "orange",
    "was it a car or a cat i saw",
    "desk",
    "did",
    "able was I ere I saw elba",
    "able was I ere I saw elba",
    "pip",
    "window",
    "eke",
    "was it a car or a cat i saw",
    "nan",
    "nooon",
    "madam in eden im adamm",
    "a man a plan a canal panama",
    "do geese see godx",
    "evil olive",
    "abcb",
    "do geese see god",
    "never a foot too far even",
    "gig",
    "eke",
    "never a foot too far even",
    "do geese see god",
    "was it a car or a cat i saw",
    "do geese see god",
    "a man a plan a canal panama",
    "wow",
    "was it a car or a cat i saw",
    "nan",
    "levvel",
    "was it a car or a cat i saw",
    "madam in eden im adamm",
    "gig",
    "phone",
    "a man a plan a canal panama",
    "do geese see godx",
    "levvel",
    "music",
    "rotorr",
    "never odd or evenn",
    "tot",
    "pip",
    "tot",
    "madam in eden im adam",
    "levvel",
    "did",
    "science",
    "never a foot too far even",
    "madam in eden im adamm",
    "science",
    "music",
    "phone",
    "wow",
    "able was I ere I saw elba",
    "able was I ere I saw elba",
    "levvel",
    "nun",
    "bottle",
    "evil olive",
    "tot",
    "nun",
    "helloo",
    "chair",
    "desk",
    "did",
    "bob",
    "desk",
    "evil olive",
    "never a foot too far even",
    "never odd or evenn",
    "did",
    "eke",
    "never odd or evenn",
    "school",
    "helloo",
    "abcb",
    "music",
    "bob",
    "gig",
    "never odd or evenn",
    "civiv",
    "do geese see godx",
    "phone",
    "nan",
    "did",
    "rotorr",
    "civiv",
    "do geese see god",
    "nun",
    "a man a plan a canal panamax",
    "bottle",
    "pip",
    "do geese see godx",
    "table",
    "tot",
    "science",
    "pip",
    "window",
    "civiv",
    "window",
    "music",
    "a man a plan a canal panama",
    "rotorr",
    "able was I ere I saw elba",
    "do geese see god",
    "table",
    "never odd or evenn",
    "madam in eden im adam",
    "a man a plan a canal panama",
    "peep",
    "madam in eden im adam",
    "pip",
    "nan",
    "never odd or evenn",
    "was it a car or a cat i saw",
    "wow",
    "nan",
    "bottle",
    "rotorr",
    "nun",
    "never a foot too far even",
    "peep",
    "school",
    "school",
    "able was I ere I saw elba",
    "pip",
    "abcb",
    "tot",
    "school",
    "able was I ere I saw elba",
    "rotorr",
    "chair",
    "do geese see god",
    "table",
    "school",
    "madam in eden im adam",
    "abcb",
    "tot",
    "do geese see godx",
    "a man a plan a canal panama",
    "do geese see godx",
    "pip",
    "phone",
    "abcb",
    "tot",
    "was it a car or a cat i saw",
    "phone",
    "was it a car or a cat i saw",
    "madam in eden im adamm",
    "eke",
    "school",
    "eke",
    "helloo",
    "did",
    "nun",
    "never a foot too far even",
    "do geese see god",
    "helloo",
    "madam in eden im adam",
    "table",
    "wow",
    "civiv",
    "madam in eden im adamm",
    "able was I ere I saw elba",
    "eke",
    "pip",
    "a man a plan a canal panamax",
    "chair",
    "levvel",
    "pip",
    "nan",
    "bottle",
    "bob",
    "never odd or evenn",
    "bottle",
    "gig",
    "tot",
    "civiv",
    "able was I ere I saw elba",
    "phone",
    "music",
    "gig",
    "wow",
    "madam in eden im adam",
    "do geese see godx",
    "did",
    "window",
    "eke",
    "was it a car or a cat i saw",
    "music",
    "phone",
    "abcb",
    "phone",
    "table",
    "a man a plan a canal panama",
    "bob",
    "tot",
    "abcb",
    "a man a plan a canal panamax",
    "wow",
    "chair",
    "chair",
    "peep",
    "able was I ere I saw elba",
    "levvel",
    "nan",
    "did",
    "window",
    "abcb",
    "a man a plan a canal panama",
    "nan",
    "never a foot too far even",
    "bottle",
    "window",
    "a man a plan a canal panamax",
    "eke",
    "gig",
    "able was I ere I saw elba",
    "tot",
    "rotorr",
    "tot",
    "never odd or evenn",
    "never odd or evenn",
    "music",
    "a man a plan a canal panamax",
    "school",
    "bob",
    "madam in eden im adam",
    "nooon",
    "bottle",
    "school",
    "able was I ere I saw elba",
    "table",
    "never a foot too far even",
    "a man a plan a canal panamax",
    "do geese see god",
    "abcb",
    "table",
    "do geese see god",
    "window",
    "do geese see god",
    "wow",
    "madam in eden im adam",
    "madam in eden im adamm",
    "table",
    "nan",
    "able was I ere I saw elba",
    "nooon",
    "abcb",
    "able was I ere I saw elba",
    "pip",
    "madam in eden im adamm",
    "orange",
    "rotorr",
    "a man a plan a canal panama",
    "eke",
    "evil olive",
    "orange",
    "never odd or evenn",
    "did",
    "tot",
    "orange",
    "tot",
    "did",
    "bottle",
    "window",
    "a man a plan a canal panamax",
    "table",
    "pip",
    "a man a plan a canal panamax",
    "tot",
    "able was I ere I saw elba",
    "bottle",
    "madam in eden im adam",
    "able was I ere I saw elba",
    "levvel",
    "gig",
    "madam in eden im adamm",
    "science",
    "gig",
    "helloo",
    "chair",
    "school",
    "was it a car or a cat i saw",
    "chair",
    "school",
    "levvel",
    "never odd or evenn",
    "table",
    "do geese see godx",
    "abcb",
    "did",
    "pip",
    "science",
    "peep",
    "bob",
    "phone",
    "nooon",
    "do geese see god",
    "bob",
    "madam in eden im adam",
    "gig",
    "bottle",
    "a man a plan a canal panama",
    "bob",
    "school",
    "evil olive",
    "able was I ere I saw elba",
    "evil olive",
    "table",
    "never a foot too far even",
    "was it a car or a cat i saw",
    "window",
    "never odd or evenn",
    "peep",
    "chair",
    "never odd or evenn",
    "bottle",
    "a man a plan a canal panama",
    "rotorr",
    "school",
    "orange",
    "nooon",
    "nooon",
    "helloo",
    "pip",
    "madam in eden im adam",
    "window",
    "science",
    "pip",
    "did",
    "do geese see godx",
    "wow",
    "never a foot too far even",
    "helloo",
    "desk",
    "orange",
    "never odd or evenn",
    "eke",
    "gig",
    "madam in eden im adamm",
    "school",
    "peep",
    "able was I ere I saw elba",
    "eke",
    "a man a plan a canal panamax",
    "peep",
    "peep",
    "civiv",
    "evil olive",
    "levvel",
    "levvel",
    "peep",
    "chair",
    "orange",
    "peep",
    "nan",
    "helloo",
    "rotorr",
    "school",
    "do geese see godx",
    "madam in eden im adam",
    "able was I ere I saw elba",
    "a man a plan a canal panamax",
    "phone",
    "school",
    "able was I ere I saw elba",
    "never odd or evenn",
    "civiv",
    "tot",
    "do geese see god",
    "civiv",
    "civiv",
    "never a foot too far even",
    "did",
    "phone",
    "levvel",
    "do geese see godx",
    "abcb",
    "civiv",
    "pip",
    "levvel",
    "gig",
    "desk",
    "bob",
    "science",
    "table",
    "pip",
    "pip",
    "desk",
    "music",
    "do geese see godx",
    "able was I ere I saw elba",
    "do geese see god",
    "levvel",
    "wow",
    "did",
    "music",
    "phone",
    "madam in eden im adamm",
    "phone",
    "peep",
    "gig",
    "do geese see god",
    "never a foot too far even",
    "a man a plan a canal panama",
    "never a foot too far even",
    "bottle",
    "bob",
    "window",
    "wow",
    "music",
    "pip",
    "gig",
    "rotorr",
    "school",
    "window",
    "gig",
    "school",
    "orange",
    "eke",
    "phone",
    "gig",
    "civiv",
    "a man a plan a canal panama",
    "madam in eden im adamm",
    "evil olive",
    "was it a car or a cat i saw",
    "a man a plan a canal panamax",
    "a man a plan a canal panamax",
    "evil olive",
    "orange",
    "do geese see god",
    "school",
    "able was I ere I saw elba",
    "abcb",
    "evil olive",
    "able was I ere I saw elba",
    "do geese see godx",
    "bob",
    "window",
    "school",
    "science",
    "school",
    "a man a plan a canal panamax",
    "chair",
    "chair",
    "was it a car or a cat i saw",
    "madam in eden im adam",
    "do geese see god",
    "levvel",
    "phone",
    "window",
    "music",
    "a man a plan a canal panama",
    "do geese see godx",
    "a man a plan a canal panamax",
    "bob",
    "abcb",
    "do geese see god",
    "school",
    "orange",
    "nan",
    "madam in eden im adamm",
    "tot",
    "table",
    "tot",
    "do geese see god",
    "able was I ere I saw elba",
    "bottle",
    "madam in eden im adamm",
    "nan",
    "phone",
    "bob",
    "madam in eden im adamm",
    "nooon",
    "nan",
    "bob",
    "wow",
    "music",
    "window",
    "never odd or evenn",
    "desk",
    "wow",
    "a man a plan a canal panama",
    "orange",
    "peep",
    "chair",
    "nan",
    "civiv",
    "table",
    "science",
    "did",
    "do geese see god",
    "never odd or evenn",
    "a man a plan a canal panama",
    "helloo",
    "desk",
    "gig",
    "orange",
    "pip",
    "madam in eden im adamm",
    "orange",
    "eke",
    "school",
    "science",
    "phone",
    "did",
    "bob",
    "did",
    "phone",
    "tot",
    "orange",
    "peep",
    "music",
    "bob",
    "eke",
    "music",
    "school",
    "never a foot too far even",
    "table",
    "do geese see god",
    "nooon",
    "phone",
    "bottle",
    "abcb",
    "bob",
    "rotorr",
    "nun",
    "nun",
    "madam in eden im adam",
    "gig",
    "a man a plan a canal panama",
    "orange",
    "phone",
    "nooon",
    "science",
    "abcb",
    "eke",
    "phone",
    "was it a car or a cat i saw",
    "a man a plan a canal panama",
    "did",
    "madam in eden im adamm",
    "never a foot too far even",
    "was it a car or a cat i saw",
    "a man a plan a canal panamax",
    "science",
    "was it a car or a cat i saw",
    "madam in eden im adamm",
    "gig",
    "nan",
    "helloo",
    "nun",
    "tot",
    "did",
    "pip",
    "science",
    "nooon",
    "did",
    "tot",
    "madam in eden im adam",
    "eke",
    "chair",
]